NumPy Array Operation

In [3]:
import numpy as np

In [8]:
arr=np.array([10,20,30,40,50])
print("basic slicing:",arr[1:4])
print("slicing with step:",arr[1:5:2])
print("negative index:",arr[-1])

basic slicing: [20 30 40]
slicing with step: [20 40]
negative index: 50


In [18]:
arr_2d=np.array([[1,2,3,10],[4,5,6,20],[7,8,9,30]])
#                 0 1 2 3    0 1 2 3    0 1 2 3
#                     0         1         2
print("entire row:",arr_2d[1:,2])
print("entire row:",arr_2d[1:,2:])
print("entire row:",arr_2d[0,:])
print("entire row:",arr_2d[1,:])
print("specific element:",arr_2d[1,2])#in row-col matrix place
print("entire column:",arr_2d[:,1])
print("entire column:",arr_2d[:,1:])
print("last 2 years sales:",arr_2d[1,2:])


entire row: [6 9]
entire row: [[ 6 20]
 [ 9 30]]
entire row: [ 1  2  3 10]
entire row: [ 4  5  6 20]
specific element: 6
entire column: [2 5 8]
entire column: [[ 2  3 10]
 [ 5  6 20]
 [ 8  9 30]]
last 2 years sales: [ 6 20]


sorting

In [ ]:
arr_1d=np.array([3,5,2,9,5,6,1,7])
print("sorted 1d array",sorted(arr_1d))
print("sorted 1d array",np.sort(arr_1d))
arr_2d=np.array([[2,1],[3,2],[1,3]])
#axis=0 for column,axis=1 for row
print("sort 2d array",np.sort(arr_2d,axis=0))
print("sort 2d array",np.sort(arr_2d,axis=1))

sorted 1d array [np.int64(1), np.int64(2), np.int64(3), np.int64(5), np.int64(5), np.int64(6), np.int64(7), np.int64(9)]
sorted 1d array [1 2 3 5 5 6 7 9]
sort 2d array [[1 1]
 [2 2]
 [3 3]]
sort 2d array [[1 2]
 [2 3]
 [1 3]]


filter

In [27]:
number=np.array([3,5,2,9,5,6,1,7])
even_number=number[number%2==0]
print("even number:",even_number)

even number: [2 6]


filter with mask

In [28]:
marks=np.array([67,34,10,23,50,97,54])
mark_pass=marks>35
print("more the 35(mark):",mark_pass)

more the 35(mark): [ True False False False  True  True  True]


index

In [30]:
sales=np.array([25000,12000,65000,80000])
idc=[1,3]
res=sales[idc]
print("find value from index:",res)

find value from index: [12000 80000]


join

In [4]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
combined=np.concatenate([arr1,arr2])
print("combined:",combined)

combined: [ 1  2  3  4 10 20 30 40]


In [5]:
matrix=np.array([[10,20],[30,40]])
newmatrix=np.array([[50,60],[70,80]])
print("join horizontal:\n",np.hstack([matrix,newmatrix]))
print("join vertical:\n",np.vstack([matrix,newmatrix]))

join horizontal:
 [[10 20 50 60]
 [30 40 70 80]]
join vertical:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


adding and removing

In [9]:
arr=np.array([1,2,3,4,5,6])
print("split:",np.split(arr,2))
print("append:",np.append(arr,50))
print("remove:",np.delete(arr,2))
print("insert:",np.insert(arr,0,90))
print("org:",arr)

split: [array([1, 2, 3]), array([4, 5, 6])]
append: [ 1  2  3  4  5  6 50]
remove: [1 2 4 5 6]
insert: [90  1  2  3  4  5  6]
org: [1 2 3 4 5 6]
