numpy functions

In [2]:
import numpy as np

aggregate function

In [3]:
arr=np.array([10,20,30,40,50])
print("sum:",np.sum(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))
print("count:",arr.size)
print("cumulitive sum:",np.cumsum(arr))
print("cumulitive product:",np.cumprod(arr))

sum: 150
Max: 50
Min: 10
count: 5
cumulitive sum: [ 10  30  60 100 150]
cumulitive product: [      10      200     6000   240000 12000000]


statical function

In [11]:
import statistics as st
sales=np.array([200,180,150,250,270,300,250,230])
print("mean:",np.mean(sales))
print("median:",np.median(sales))
print("mode:",st.mode(sales))
print("standard deviation:",np.std(sales))

mean: 228.75
median: 240.0
mode: 250
standard deviation: 46.21620386834038


In [13]:
price=np.array([120,180,200,210,220,300])
sales=np.array([15,13,10,17,29,25])
print(np.corrcoef([price,sales]))

[[1.         0.57982339]
 [0.57982339 1.        ]]


In [3]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original matrix:")
print(a)
a = np.append(a, [[7, 8, 9]], axis=0)
print("\nAfter adding a row:")
print(a)
a = np.append(a, [[10], [11], [12]], axis=1)
print("\nAfter adding a column:")
print(a)
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a = np.insert(a, 2, [10, 11, 12], axis=0)
print("\nAfter inserting a row:")
print(a)
a = np.insert(a, 1, [20, 21, 22, 23], axis=1)
print("\nAfter inserting a column:")
print(a)
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a = np.delete(a, 1, axis=0)
print("\nAfter removing a row:")
print(a)
a = np.delete(a, 1, axis=1)
print("\nAfter removing a column:")
print(a)

Original matrix:
[[1 2 3]
 [4 5 6]]

After adding a row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding a column:
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]

After inserting a row:
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [ 7  8  9]]

After inserting a column:
[[ 1 20  2  3]
 [ 4 21  5  6]
 [10 22 11 12]
 [ 7 23  8  9]]

After removing a row:
[[1 2 3]
 [7 8 9]]

After removing a column:
[[1 3]
 [7 9]]


In [4]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:")
print(np.add(a, b))

print("\nSubtraction:")
print(np.subtract(a, b))

print("\nMultiplication:")
print(np.multiply(a, b))

print("\nDivision:")
print(np.divide(a, b))

print("\nPower:")
print(np.power(a, 2))

print("\nSquare root:")
print(np.sqrt(a))

Addition:
[12 24 35 48]

Subtraction:
[ 8 16 25 32]

Multiplication:
[ 20  80 150 320]

Division:
[5. 5. 6. 5.]

Power:
[ 100  400  900 1600]

Square root:
[3.16227766 4.47213595 5.47722558 6.32455532]


In [5]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],
    [2, 120000, 140000, 160000, 190000],
    [3, 200000, 230000, 260000, 300000],
    [4, 180000, 210000, 240000, 270000],
    [5, 160000, 185000, 205000, 230000]
])

# 1. Shape of the data
print("1. Shape of the data:")
print(sales_data.shape)

# 2. Print sample data for first 3 restaurants
print("\n2. First 3 restaurants:")
print(sales_data[:3])

# 3. Total sales per year
total_sales_per_year = np.sum(sales_data[:, 1:], axis=0)
print("\n3. Total sales per year:")
print(total_sales_per_year)

# 4. Maximum sale per restaurant
max_sales = np.max(sales_data[:, 1:], axis=1)
print("\n4. Maximum sale per restaurant:")
print(max_sales)

# 5. Maximum sale every year
max_sales_per_year = np.max(sales_data[:, 1:], axis=0)
print("\n5. Maximum sale every year:")
print(max_sales_per_year)

# 6. Average sale of each restaurant
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("\n6. Average sale of each restaurant:")
print(avg_sales)

# 7. Average cumulative sales for all restaurants
cumulative_sales = np.sum(sales_data[:, 1:], axis=1)
average_cumulative_sales = np.mean(cumulative_sales)
print("\n7. Average cumulative sales for all restaurants:")
print(average_cumulative_sales)

# 8. Monthly average for all restaurants every year
yearly_total = np.sum(sales_data[:, 1:], axis=0)
monthly_average = yearly_total / 12
print("\n8. Monthly average for all restaurants every year:")
print(monthly_average)

1. Shape of the data:
(5, 5)

2. First 3 restaurants:
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

3. Total sales per year:
[ 810000  945000 1085000 1240000]

4. Maximum sale per restaurant:
[250000 190000 300000 270000 230000]

5. Maximum sale every year:
[200000 230000 260000 300000]

6. Average sale of each restaurant:
[200000. 152500. 247500. 225000. 195000.]

7. Average cumulative sales for all restaurants:
816000.0

8. Monthly average for all restaurants every year:
[ 67500.          78750.          90416.66666667 103333.33333333]
